name: check pr title

on:
  pull_request:
    types: [opened, edited]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: "(?:build|ci|docs|feat|fix|perf|refactor|test)!?: [a-z]{1}.+[a-zA-Z0-9]{1}"
          helpMessage: "Please use PR title being first line of a conventional commit, see https://www.conventionalcommits.org/en/v1.0.0/"
